import type { JourneyResult } from "@/lib/emissions";
import { formatCo2, formatDuration } from "@/lib/emissions";

// ─────────────────────────────────────────────────────────────────
// CSV export — works with Entur journey results
// ─────────────────────────────────────────────────────────────────

export function exportCsv(
  journeys: JourneyResult[],
  from: string,
  to: string,
  distanceKm: number,
  workDays: number
) {
  const rows: string[][] = [
    ["CO2 Route Calculator — Norway", "", "", "", ""],
    [`Route: ${from} → ${to}`, `Distance: ${distanceKm} km`, `Work days/year: ${workDays}`, "", ""],
    ["Sources: Entur Journey Planner · EEA (estimated specific CO₂ by mode) · Miljødirektoratet · SINTEF Energimodul (ISO 14083:2023)", "", "", "", ""],
    [""],
  ];

  if (journeys.length > 0) {
    rows.push(["JOURNEY OPTIONS (Entur)", "", "", "", ""]);
    rows.push(["Option", "Legs", "Total CO₂ (kg)", "Annual CO₂ (kg)", "Duration"]);
    journeys.forEach((j, i) => {
      const legDesc = j.legs
        .map((l) => `${l.mode} ${l.fromName}→${l.toName}`)
        .join(" | ");
      rows.push([
        `Option ${i + 1}`,
        legDesc,
        j.totalCo2Kg.toString(),
        j.annualCo2Kg.toString(),
        formatDuration(j.durationMinutes),
      ]);
    });

    // Leg breakdown for option 1
    const best = journeys[0];
    rows.push([""]);
    rows.push(["ROUTE BREAKDOWN — Option 1", "", "", "", ""]);
    rows.push(["From", "To", "Mode", "Distance (km)", "CO₂ (kg)", "Operator", "Line"]);
    best.legs.forEach((l) => {
      rows.push([
        l.fromName, l.toName, l.mode,
        l.distanceKm.toString(), l.co2Kg.toString(),
        l.operatorName ?? "", l.lineName ?? "",
      ]);
    });
  }

  const csv = rows
    .map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(","))
    .join("\n");

  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `co2-route-${from}-${to}.csv`
    .replace(/\s+/g, "-").replace(/[^a-z0-9.\-]/gi, "").toLowerCase();
  a.click();
  URL.revokeObjectURL(url);
}

// ─────────────────────────────────────────────────────────────────
// CSRD Scope 3 text export
// ─────────────────────────────────────────────────────────────────

export function exportCsrdText(
  journeys: JourneyResult[],
  from: string,
  to: string,
  distanceKm: number,
  workDays: number
): string {
  const best = journeys[0] ?? null;

  const lines: string[] = [
    "CSRD SCOPE 3 — EMPLOYEE COMMUTE EMISSIONS REPORT",
    "Generated by CO₂ Route Calculator · github.com/irinaaf",
    "",
    `Route analysed:       ${from} → ${to}`,
    `Straight-line dist.:  ${distanceKm} km`,
    `Work days per year:   ${workDays}`,
    `Calculation date:     ${new Date().toISOString().slice(0, 10)}`,
    "",
  ];

  if (best) {
    lines.push("RECOMMENDED ROUTE (lowest CO₂ via Entur Journey Planner):");
    lines.push(`  Total:    ${formatCo2(best.totalCo2Kg)} per trip  |  Annual: ${formatCo2(best.annualCo2Kg)}`);
    lines.push(`  Duration: ${formatDuration(best.durationMinutes)}`);
    lines.push("");
    lines.push("  Leg breakdown:");
    best.legs.forEach((l) => {
      const coeff = `${(l.co2PerKm * 1000).toFixed(1)} g/pkm`;
      lines.push(
        `  · ${l.fromName.padEnd(22)} → ${l.toName.padEnd(22)}` +
        `  ${l.mode.padEnd(14)}` +
        `  ${coeff} × ${l.distanceKm} km = ${formatCo2(l.co2Kg)}`
      );
      if (l.operatorName) lines.push(`    Operator: ${l.operatorName}${l.lineName ? ` · Line ${l.lineName}` : ""}`);
    });
    lines.push("");

    if (journeys.length > 1) {
      lines.push(`ALL JOURNEY OPTIONS (${journeys.length} total):`);
      journeys.forEach((j, i) => {
        lines.push(`  Option ${i + 1}:  ${formatCo2(j.totalCo2Kg)}/trip  |  Annual: ${formatCo2(j.annualCo2Kg)}  |  ${formatDuration(j.durationMinutes)}`);
      });
      lines.push("");
    }
  } else {
    lines.push("No public transport routes found via Entur for this route.");
    lines.push("");
  }

  lines.push("METHODOLOGY:");
  lines.push("Routes sourced from Entur Journey Planner API v3 (real timetable + OpenStreetMap data).");
  lines.push("Emission factors: EEA — Estimated specific emissions of CO₂ by mode of transport");
  lines.push("  (eea.europa.eu/en/analysis/maps-and-charts/estimated-specific-emissions-of-co2).");
  lines.push("Norwegian public transport: Entur + SINTEF Energimodul (miljo.entur.org), ISO 14083:2023.");
  lines.push("Car factors: Miljødirektoratet Norwegian fleet average (miljostatus.miljodirektoratet.no).");
  lines.push("Norwegian rail: 0.009 kg CO₂e/pkm (Vy, ~99% hydropower).");
  lines.push("Ferry: 0.019 kg CO₂e/pkm (Norled/Fjord1 fleet average 2023).");
  lines.push("Bus: operator-specific factor where available (Ruter 0.011, AtB 0.018, regional 0.027).");
  lines.push("Aviation: includes IPCC radiative forcing multiplier ×1.9.");
  lines.push("Road distance: OSRM / OpenStreetMap (switchable to Google Maps via env vars).");
  lines.push("");
  lines.push("Scope: ESRS E1-6, GHG Protocol Category 3.7 — Employee commuting.");

  return lines.join("\n");
}
