import type { JourneyResult } from "@/lib/emissions";
import { formatCo2, formatDuration } from "@/lib/emissions";

/** Selected journey passed from the UI toggle — may be a transit leg or a synthetic car entry */
export type SelectedJourney = JourneyResult & { label?: string };

// ─────────────────────────────────────────────────────────────────
// CSV export — works with Entur journey results
// ─────────────────────────────────────────────────────────────────

export function exportCsv(
  journeys: JourneyResult[],
  selectedJourney: SelectedJourney | null,
  from: string,
  to: string,
  distanceKm: number,
  workDays: number
) {
  const rows: string[][] = [
    ["CO2 Route Calculator — Norway", "", "", "", ""],
    [`Route: ${from} → ${to}`, `Distance: ${distanceKm} km`, `Work days/year: ${workDays}`, "", ""],
    ["Sources: Entur Journey Planner · EEA (estimated specific CO₂ by mode) · Miljødirektoratet · SINTEF Energimodul (ISO 14083:2023)", "", "", "", ""],
    [""],
  ];

  if (journeys.length > 0) {
    rows.push(["JOURNEY OPTIONS (Entur)", "", "", "", ""]);
    rows.push(["Option", "Legs", "Total CO₂ (kg)", "Annual CO₂ (kg)", "Duration"]);
    journeys.forEach((j, i) => {
      const legDesc = j.legs
        .map((l) => `${l.mode} ${l.fromName}→${l.toName}`)
        .join(" | ");
      rows.push([
        `Option ${i + 1}`,
        legDesc,
        j.totalCo2Kg.toString(),
        j.annualCo2Kg.toString(),
        formatDuration(j.durationMinutes),
      ]);
    });
  }

  if (selectedJourney) {
    rows.push([""]);
    const isCar = selectedJourney.legs.length === 0 && !!selectedJourney.label;
    if (isCar) {
      rows.push(["SELECTED ROUTE — Private car", "", "", "", ""]);
      rows.push(["Mode", "Total CO₂ (kg)", "Annual CO₂ (kg)", "", ""]);
      rows.push([
        selectedJourney.label ?? "",
        selectedJourney.totalCo2Kg.toString(),
        selectedJourney.annualCo2Kg.toString(),
        "",
        "",
      ]);
    } else if (selectedJourney.legs.length > 0) {
      rows.push(["SELECTED ROUTE BREAKDOWN", "", "", "", ""]);
      rows.push(["From", "To", "Mode", "Distance (km)", "CO₂ (kg)", "Operator", "Line"]);
      selectedJourney.legs.forEach((l) => {
        rows.push([
          l.fromName, l.toName, l.mode,
          l.distanceKm.toString(), l.co2Kg.toString(),
          l.operatorName ?? "", l.lineName ?? "",
        ]);
      });
    }
  }

  const csv = rows
    .map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(","))
    .join("\n");

  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `co2-route-${from}-${to}.csv`
    .replace(/\s+/g, "-").replace(/[^a-z0-9.\-]/gi, "").toLowerCase();
  a.click();
  URL.revokeObjectURL(url);
}

// ─────────────────────────────────────────────────────────────────
// CSRD Scope 3 text export
// ─────────────────────────────────────────────────────────────────

export function exportCsrdText(
  journeys: JourneyResult[],
  selectedJourney: SelectedJourney | null,
  reportingBasis: string,
  from: string,
  to: string,
  distanceKm: number,
  workDays: number
): string {
  const lines: string[] = [
    "CSRD SCOPE 3 — EMPLOYEE COMMUTE EMISSIONS REPORT",
    "Generated by CO₂ Route Calculator · github.com/irinaaf",
    "",
    `Route analysed:       ${from} → ${to}`,
    `Straight-line dist.:  ${distanceKm} km`,
    `Work days per year:   ${workDays}`,
    `Calculation date:     ${new Date().toISOString().slice(0, 10)}`,
    `Reporting basis:      ${reportingBasis}`,
    "",
  ];

  if (selectedJourney) {
    const isCar = selectedJourney.legs.length === 0 && !!selectedJourney.label;
    if (isCar) {
      lines.push("SELECTED ROUTE:");
      lines.push(`  Mode:     ${selectedJourney.label} (private car)`);
      lines.push(`  Total:    ${formatCo2(selectedJourney.totalCo2Kg)} per trip  |  Annual: ${formatCo2(selectedJourney.annualCo2Kg)}`);
      lines.push("  Note: Solo driver assumption per GHG Protocol Category 7.");
      lines.push("        Car ferry crossings are shown separately if detected on route.");
      lines.push("");
    } else {
      lines.push("SELECTED ROUTE:");
      lines.push(`  Total:    ${formatCo2(selectedJourney.totalCo2Kg)} per trip  |  Annual: ${formatCo2(selectedJourney.annualCo2Kg)}`);
      if (selectedJourney.durationMinutes > 0) {
        lines.push(`  Duration: ${formatDuration(selectedJourney.durationMinutes)}`);
      }
      lines.push("");
      if (selectedJourney.legs.length > 0) {
        lines.push("  Leg breakdown:");
        selectedJourney.legs.forEach((l) => {
          const coeff = `${(l.co2PerKm * 1000).toFixed(1)} g/pkm`;
          lines.push(
            `  · ${l.fromName.padEnd(22)} → ${l.toName.padEnd(22)}` +
            `  ${l.mode.padEnd(14)}` +
            `  ${coeff} × ${l.distanceKm} km = ${formatCo2(l.co2Kg)}`
          );
          if (l.operatorName) lines.push(`    Operator: ${l.operatorName}${l.lineName ? ` · Line ${l.lineName}` : ""}`);
        });
        lines.push("");
      }
    }
  } else {
    lines.push("No routes found for this selection.");
    lines.push("");
  }

  if (journeys.length > 0) {
    lines.push(`ALL TRANSIT OPTIONS (${journeys.length} total, for reference):`);
    journeys.forEach((j, i) => {
      lines.push(`  Option ${i + 1}:  ${formatCo2(j.totalCo2Kg)}/trip  |  Annual: ${formatCo2(j.annualCo2Kg)}  |  ${formatDuration(j.durationMinutes)}`);
    });
    lines.push("");
  }

  lines.push("METHODOLOGY:");
  lines.push("Routes sourced from Entur Journey Planner API v3 (real timetable + OpenStreetMap data).");
  lines.push("Emission factors: EEA — Estimated specific emissions of CO₂ by mode of transport");
  lines.push("  (eea.europa.eu/en/analysis/maps-and-charts/estimated-specific-emissions-of-co2).");
  lines.push("Norwegian public transport: Entur + SINTEF Energimodul (miljo.entur.org), ISO 14083:2023.");
  lines.push("Car factors: Miljødirektoratet Norwegian fleet average (miljostatus.miljodirektoratet.no).");
  lines.push("Norwegian rail: 0.009 kg CO₂e/pkm (Vy, ~99% hydropower).");
  lines.push("Ferry: 0.019 kg CO₂e/pkm (Norled/Fjord1 fleet average 2023).");
  lines.push("Bus: operator-specific factor where available (Ruter 0.011, AtB 0.018, regional 0.027).");
  lines.push("Aviation: includes IPCC radiative forcing multiplier ×1.9.");
  lines.push("Road distance: OSRM / OpenStreetMap (switchable to Google Maps via env vars).");
  lines.push("");
  lines.push("Scope: ESRS E1-6, GHG Protocol Category 3.7 — Employee commuting.");

  return lines.join("\n");
}
